config/routes.rb
Markmy::Application.routes.draw do
  devise_for :users, :controllers => { registrations: :registrations, sessions: :sessions }

  namespace :admin do
    resources :predictions, only: [:index]
  end

  resources :blurbs, :path => :words, only: [:show, :create, :destroy, :update] do
    get :update_background
  end
  get '/my_predictions' => 'blurbs#index', :as => 'my_blurbs'

  root to: redirect('/words')
  get '/words' => 'application#home', :as => 'home'

  get 'user_home' => redirect('/my_predictions'), :as => 'user_root'

  get 'worldcup' => 'worldcup#root'
end

app/models/blurb.rb
class Blurb < ActiveRecord::Base

  TOKEN_LENGTH = 10

  after_initialize :set_default_values
  validates_presence_of :token, :text

  belongs_to :user

  mount_uploader :custom_background, BackgroundUploader

  default_scope { order(:created_at) }

  is_impressionable counter_cache: true, unique: true

  def empty?
    text.blank?
  end

  def to_param
    self.token
  end

  def username
    user.try(:name).presence || 'Anonymous'
  end

  def background
    if custom_background?
      custom_background_url
    else
      image_url
    end
  end

  def custom_background?
    custom_background.present?
  end

  def image_attribution
    @_image_info ||= image_list.info_for_url(image_url)
  end

  def mood
    return nil if custom_background?
    @_mood ||= image_attribution.mood
  end

  def mood=(mood)
    self.remove_custom_background!
    self.image_url = image_list.random_image(mood, self.image_url)
  end

  def color
    image_list.color_for_url(background)
  end

  private

  def set_default_values
    self.image_url ||= image_list.random_image
    self.token  ||= SecureRandom.urlsafe_base64(TOKEN_LENGTH)
    self.time   ||= DateTime.now
  end

  def image_list
    @_images ||= Images.new
  end

end

app/controllers/blurbs_controller.rb
class BlurbsController < ApplicationController
  before_action :current_blurb, only: [:show, :destroy, :update, :update_background]

  before_filter :authenticate_user!, only: [:index, :update, :update_background]


  def index
    @title = I18n.translate('my_predictions')
    @blurbs = current_user.blurbs
  end

  def show
    impressionist(@blurb)
    @uploader = @blurb.custom_background
    @uploader.success_action_redirect = blurb_update_background_url(@blurb)
  end

  def create
    render inline: '', status: 500 and return if current_user.guest_account? and (blurb_params[:text].include?('a href') or blurb_params[:text].include?('http'))

    @blurb = create_blurb

    if @blurb.save
      redirect_to @blurb
    else
      render action: 'home'
    end
  end

  def update
    @blurb.update(edit_blurb_params)
    redirect_to @blurb
  end

  def update_background
    @blurb.update(key: params.require(:key))
    redirect_to @blurb
  end

  def destroy
    @blurb.destroy
    redirect_to blurbs_url
  end

  private
  def current_blurb
    @blurb ||= Blurb.find_by(token: params[:blurb_id].presence || params[:id])
    @title = @blurb.text
  end

  def blurb_params
    params.require(:blurb).permit(:text, :mood)
  end

  def edit_blurb_params
    params.require(:blurb).permit(:mood)
  end

  def create_blurb
    create_and_sign_in_guest_account unless user_signed_in?
    current_user.blurbs.build(blurb_params)
  end

end

app/helpers/blurbs_helper.rb
module BlurbsHelper

  def twitter_share_url
    'https://twitter.com/share?' + {
      url: blurb_url(@blurb),
      text: t('blurb.share_description'),
      via: 'MarkMyApp'
    }.to_param
  end

  def facebook_share_url
    'https://www.facebook.com/sharer/sharer.php?' + {
      u: blurb_url(@blurb),
    }.to_param
  end


  def author?
    @blurb.user == current_user
  end

  def blurb_user_attributes
    return {} unless author?
    if current_user.guest_account?
      {
        class: 'user has-popover has-link',
        data: {
        url: edit_user_registration_path,
        toggle: 'popover',
        placement: 'bottom',
        container: 'body',
        trigger: 'hover',
        # title: '<i class="fa fa-user"></i> Click to set your name',
        html: 'true',
        # content: 'You are using a temporary guest account, click to <strong>Create Account</strong> and set your name.'}
        content:  '<i class="fa fa-user"></i> Click to set your name'
        }
      }
    else
      {}
    end
  end
end

app/views/blurbs/_change_image.html.haml
.change-image
  %button.btn.btn-sm.change-image-button{data: {container: 'body', toggle: 'popover', placement: 'bottom'}}
    %i.fa.fa-picture-o
  .moods.hidden
    = form_for(@blurb) do |f|
      .btn-group
        %p= t('blurb.background.title')
        - Images.moods.each do |mood|
          %button.btn.btn-block.btn-default.btn-change-img{type: 'submit', name: 'blurb[mood]', value: mood, class: @blurb.mood==mood && 'btn-primary'}
            - if @blurb.mood==mood
              %i.fa.fa-refresh.text-right
            %span= mood.capitalize

    %br
    = direct_upload_form_for @uploader, :'data-no-turbolink'=> true do |f|
      = f.file_field :image_url, class: 'hidden file-input', accept: "image/*"
      %button.btn-upload-file.btn.btn-block.btn-default{type: 'button'}
        %span.before
          %i.fa.fa-picture-o
          %span= t('blurb.background.upload.before')
        %span.during.hidden
          %i.fa.fa-spinner.fa-spin
          %span= t('blurb.background.upload.during')

app/views/blurbs/_image_with_text.html.haml
.blurb
  .bg
    .img
      = image_tag(blurb.background)
  .content
    .text
      %span
        = blurb.text
      .timeago{'data-livestamp' => blurb.time.to_i} #{time_ago_in_words(blurb.time)} ago
    .by
      = image_tag(avatar_url(blurb.user), class: 'avatar')
      %span= t('blurb.who', user: blurb.username)

app/views/blurbs/_thumbnail.html.haml
= link_to blurb_path(blurb), class: 'blurbnail' do
  = render 'blurbs/image_with_text', blurb: blurb

app/views/blurbs/_views.html.haml
.number_of_views
  %button.btn.btn-sm.btn-transparent.btn-views{data: {container: 'body', toggle: 'tooltip', placement: 'bottom', title: t('.views', count: @blurb.impressions_count)}}
    %i.fa.fa-eye
    = @blurb.impressions_count

app/views/blurbs/index.html.haml
#my-blurbs-page
  - if @blurbs.empty?
    .text-center
      %h1
        %i.fa.fa-frown-o
        = t('.no_predictions')
      %p
        = t('.you_dont_have_any_predictions_')
        = t('.create_your_first_prediction_t')
      = link_to t('.create_my_first_prediction'), new_blurb_path, class: 'btn btn-default btn-md'

  - else
    %h1= t('my_predictions')
    - if current_user.guest_account?
      %p
        %i.fa.fa-warning-sign.fa-lg
        %strong #{t('note')}:
        %span= t('my_predictions_page.note.a')
        = link_to t('.create_account'), edit_user_registration_path
        %span= t('my_predictions_page.note.b')

    .row
      - @blurbs.each do |blurb|
        = render 'blurbs/thumbnail', blurb: blurb

app/views/blurbs/show.html.haml
- content_for :on_body do
  .bg-img
    .bgg{:style => "background-image: url('#{@blurb.background}')"}

  - unless @blurb.custom_background?
    .img-attribution
      = t('image_attribution')
      = link_to @blurb.image_attribution.author, @blurb.image_attribution.src, target: :_blank


#prediction-page
  .prediction-poster{:style => "background-color: #{@blurb.color}"}
    .content
      .text
        %strong= @blurb.text
        .attribution
          %span{ blurb_user_attributes }= t('.username', :username => (@blurb.username))
          %span.timeago
            %span= simple_date(@blurb.time)
            %small.live
              %span{'data-livestamp' => @blurb.time.to_i}= t('.timeago', time: time_ago_in_words(@blurb.time))
  .notice!= t('.notice', time: @blurb.time)

  .share-buttons.row.text-center
    = link_to facebook_share_url, target: :_blank , class: 'btn-share btn-share-facebook', data: {width: 600, height: 300}  do
      %i.fa.fa-facebook
    = link_to twitter_share_url, target: :_blank , class: 'btn-share btn-share-twitter', data: {width: 550, height: 420}  do
      %i.fa.fa-twitter
    = mail_to nil, subject: t('.email-subject'), body: t('.email-body', text: @blurb.text.strip, username: @blurb.username, timeago: t('.timeago', time: time_ago_in_words(@blurb.time)), link: blurb_url(@blurb)), class: 'btn-share btn-share-mail' do
      %i.fa.fa-envelope
    = link_to blurb_url(@blurb), class: 'btn-share btn-share-link' do
      %i.fa.fa-link

- if author?
  .author_toolbar
    = render 'blurbs/views'
    = render 'blurbs/change_image'