config/routes.rb
Markmy::Application.routes.draw do
  devise_for :users, :controllers => { registrations: :registrations, sessions: :sessions }

  namespace :admin do
    resources :predictions, only: [:index]
  end

  resources :blurbs, :path => :words, only: [:show, :create, :destroy, :update] do
    get :update_background
  end
  get '/my_predictions' => 'blurbs#index', :as => 'my_blurbs'

  root to: redirect('/words')
  get '/words' => 'application#home', :as => 'home'

  get 'user_home' => redirect('/my_predictions'), :as => 'user_root'

  get 'worldcup' => 'worldcup#root'
end

app/views/layouts/_flash.html.haml
- if notice.present?
  .alert.alert-success= notice
- if alert.present?
  .alert.alert-danger= alert

app/views/layouts/_footer.html.haml
.footer
  .container.text-center
    = link_to t('.yonbergman'), 'https://twitter.com/yonbergman'
    &amp;
    = link_to t('.giladgo'), 'https://twitter.com/giladgo'
    = t('site.footer.copyright')

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default{role: 'navigation'}
  .container
    .container-fluid
      .navbar-header
        %button.navbar-toggle{"data-target" => "#navigation-actions", "data-toggle" => "collapse", type: "button"}
          %span.sr-only= t('.toggle_navigation')
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: root_path}
          %i.fa.fa-bookmark
          = t('site.title')
      #navigation-actions.collapse.navbar-collapse
        %ul.nav.navbar-nav
          - unless @in_home
            %li
              = link_to root_path do
                %i.fa.fa-plus
                = t('nav.create_prediction')
          %li
            = link_to my_blurbs_path do
              %i.fa.fa-list-ul
              = t('my_predictions')
          - if admin_signed_in?
            %li
              = link_to admin_predictions_path do
                %i.fa.fa-dashboard
                = t('nav.admin.dashboard')
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            - if current_user.guest_account?
              %li
                = link_to t('nav.user.sign_in'), new_user_session_path
              %li
                = link_to t('nav.user.create_account'), edit_user_registration_path
            - else
              %li
                .navbar-text
                  %span= t('nav.user.signed_in_as')
                  %strong= current_user.name
              %li
                = link_to t('nav.user.sign_out'), destroy_user_session_path, method: 'DELETE'
          - else
            %li
              = link_to t('nav.user.sign_in'), new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html.no-js{:lang => 'en'}
  %head
    %meta{:charset => 'utf-8'}
    %title= title
    %meta{:name => 'description', :content => description}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'}
    %meta{:property => 'og:title', :content => title}
    %meta{:property => 'og:description', :content => description}
    %meta{:property => 'og:image', :content => image_url('icon200.png')}
    %link{:href => '/favicon.png', :rel => 'shortcut icon'}
    = csrf_meta_tags
    = stylesheet_link_tag :application
    = javascript_include_tag :application

  %body
    = render 'layouts/ga'
    = render 'layouts/nav'
    = yield :on_body
    .container.main-container{class: @noheight && 'no-height'}
      = yield
      = render 'layouts/footer'